name: flylens
description: A front application for the EIP Project FlyLens.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  #------ UTILS ------#
  http: ^0.13.5
  fluttertoast: ^8.1.1
  page_transition: ^2.0.5
  weather: ^2.0.1
  iconsax: ^0.0.8
  flutter_spinkit: ^5.1.0
  animations: ^2.0.3
  floating_bottom_navigation_bar: ^1.5.2
  auto_size_text: ^3.0.0
  flutter_map: ^3.0.0
  flutter_screenutil: ^5.5.3+2
  localstorage: ^4.0.0+1
  flutter_colorpicker: ^1.0.3
  uuid: ^3.0.6
  intl_phone_number_input: ^0.7.0+2
  datetime_picker_formfield: ^2.0.1
  flutter_svg: ^1.1.4
  cached_network_image: ^3.2.2
  google_nav_bar: ^5.0.6
  url_launcher: ^6.1.7
  flutter_riverpod: ^2.3.6
  timeago_flutter: ^3.4.0
  photo_view: ^0.14.0
  image_picker: ^0.8.9
  dependency_validator: ^3.2.2
  flutter_localization: ^0.1.12
  #-------------------#

  #------ JSON SERIALIZE ------#
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  #----------------------------#

  #------ QR CODE SCAN & GENERATE PACKAGES ------#
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  #----------------------------------------------#


  #------ AUTH & FIREBASE PACKAGES ------#
  flutter_facebook_auth: ^5.0.6
  google_sign_in: ^5.4.1
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.3
  firebase_core: ^2.10.0
  google_place: ^0.4.7
  firebase_crashlytics: ^3.3.3
  #--------------------------------------#


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_app.png"

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  build_runner: ^2.1.10
  freezed: ^2.1.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf   
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/video/
    - assets/svg/
    - assets/image/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
